//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NgCooking_Asp.net.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comments
    {
        public int commentsId { get; set; }
        public string RecettesrecettesId { get; set; }
        public int UserId { get; set; }
        public string comment { get; set; }
        public int mark { get; set; }
        public string title { get; set; }
    
        public virtual Recettes Recettes { get; set; }
    }
}
