//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NgCooking_Asp.net.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Communaute
    {
        public int id { get; set; }
        public string Bio { get; set; }
        public int Birth { get; set; }
        public string City { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public int Level { get; set; }
        public string Password { get; set; }
        public string Picture { get; set; }
        public string Surname { get; set; }
    }
}
